CREATE TABLE IF NOT EXISTS rooms (pin TEXT PRIMARY KEY, token TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS files (id INTEGER PRIMARY KEY AUTOINCREMENT, room_pin TEXT NOT NULL, object_key TEXT NOT NULL, name TEXT NOT NULL, bytes INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS files_room ON files(room_pin);
